In [1]:
import pandas as pd

In [5]:
a={
    'Name':['jatin','abahy','vishal','tanmay','rohit','romit','rahul'],
    'age':[25,36,21,36,24,41,56],
    'score':[96,25,45,78,40,56,23]

}
data=pd.DataFrame(a)
data

     Name  age  score
0   jatin   25     96
1   abahy   36     25
2  vishal   21     45
3  tanmay   36     78
4   rohit   24     40
5   romit   41     56
6   rahul   56     23

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   age     7 non-null      int64
 2   score   7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [10]:
data.head()#top 5 rows

     Name  age  score
0   jatin   25     96
1   abahy   36     25
2  vishal   21     45
3  tanmay   36     78
4   rohit   24     40

In [11]:
data.shape

(7, 3)

In [12]:
data.tail()

     Name  age  score
2  vishal   21     45
3  tanmay   36     78
4   rohit   24     40
5   romit   41     56
6   rahul   56     23

In [13]:
data.dtypes

Name     object
age       int64
score     int64
dtype: object

**selecting rows and columns**

In [15]:
data[['Name','age']]

     Name  age
0   jatin   25
1   abahy   36
2  vishal   21
3  tanmay   36
4   rohit   24
5   romit   41
6   rahul   56

In [20]:
data.loc[4,'Name']
#.loc(df.loc[row_label,col_label])

'rohit'

In [25]:
data.loc[1:4,['Name','age']]

     Name  age
1   abahy   36
2  vishal   21
3  tanmay   36
4   rohit   24

In [26]:
#.iloc(row_index,col_index)
data.iloc[3]

Name     tanmay
age          36
score        78
Name: 3, dtype: object

In [27]:
data.iloc[0:3,0:2]

     Name  age
0   jatin   25
1   abahy   36
2  vishal   21

In [28]:
data.index

RangeIndex(start=0, stop=7, step=1)

In [29]:
data.values

array([['jatin', 25, 96],
       ['abahy', 36, 25],
       ['vishal', 21, 45],
       ['tanmay', 36, 78],
       ['rohit', 24, 40],
       ['romit', 41, 56],
       ['rahul', 56, 23]], dtype=object)

In [30]:
data.columns

Index(['Name', 'age', 'score'], dtype='object')

In [31]:
data.values.shape

(7, 3)